### ISSUE TITLE
Bug: Missing library in default Ubuntu 22.04 installation. (Includes fix.)

### ISSUE THREAD

**Issue by haxys** [arenatemp/sd-tagging-helper#11]
While attempting to install and use this application in Ubuntu, I followed the installation instructions, yet couldn't get the app to run. There was a complaint about a missing QT5 runtime. It turns out, `libxcb-xinerama0` is not installed by default in 22.04; since this library was required by your application (whether because of the app itself or because of Python), the application wouldn't run without it.

To fix the issue, I simply did: `sudo apt install libxcb-xinerama0 -y` — after this, the app loaded fine.

I haven't had a chance to continue testing, but hope you can add this to the `README.md` to help future taggers using Ubuntu.

**Comment by arenasys** [comment]
Ubuntu also has the package `python3-pyqt5`, which seems like the canon way to install pyqt5. did you try this?
