### ISSUE TITLE
Crash when trying to crop

### ISSUE THREAD

**Issue by KutsuyaYuki** [arenatemp/sd-tagging-helper#12]
When selecting face and pressing CTRL+E the app crashes with the following error:
`qrc:/Output.qml:14:9: QML CenteredImage: Failed to get image from provider: image://preview/2.png
`

**Comment by arenasys** [comment]
this shouldn't cause a crash if it occurred since its just in the frontend. check the crash.log file for the backend error

**Comment by arenasys** [comment]
rewrote the preview backend so im gonna close this
