### ISSUE TITLE
help installing danbooru to sd-tagger-helper

### ISSUE THREAD

**Issue by Tortellin1** [arenatemp/sd-tagging-helper#20]
as far as I know, and according to the instructions, I have deepdanbooru correctly installed. the problem I'm having is when I click "load Deepdanbooru?" on the left of the menu, I do not know where to select as deepdanbooru. someone please help!
![201333311-31d5f878-8a45-4343-a026-4bf31c89b65b](https://user-images.githubusercontent.com/117955345/201426009-806b62b3-9923-4190-b1fa-cac496fdaf0c.png)

**Comment by arenasys** [comment]
https://github.com/arenatemp/sd-tagging-helper#deepdanbooru

**Comment by Tortellin1** [comment]
> https://github.com/arenatemp/sd-tagging-helper#deepdanbooru

where is the interrogate button? I cannot find that anywhere in the application
all I see is a spot on the left menu that when I hover over it, it says "load DeepDanbooru?"
If I right click that place, it gives me this:
![image](https://user-images.githubusercontent.com/117955345/201458107-62fb0c65-90ae-4e0b-95ef-299b48372b5d.png)

neither of those interrogate options does anything when I select them.

Note: if I click load deepdanbooru? it will take me to file explorer. hence my first question, where do I select as deepdanbooru?

**Comment by arenasys** [comment]
the button with the interrogate actions is the interrogate button.
press it then select your stable-diffusion-webui folder.

**Comment by Tortellin1** [comment]
here is my stable-diffusion-webui folder:
![image](https://user-images.githubusercontent.com/117955345/201501694-3f9ea519-d959-4c87-8757-20a64639577e.png)

I click it select at stable-diffusion-webui, then the application closes. I reload the application, and it shows this:
![image](https://user-images.githubusercontent.com/117955345/201501726-50ba7b6d-da9b-49c9-9f83-39010cc81275.png)

I will keep this application open and update if anything changes, but right now it is stuck saying loading...

edit: 2 hours passed and still on loading... I am certain I selected the correct folder

**Comment by arenasys** [comment]
are there any errors shown in the terminal or in crash.log?

**Comment by Tortellin1** [comment]
![image](https://user-images.githubusercontent.com/117955345/201542496-0ab10178-3160-4e1e-9b6d-17072d8c2901.png)
seems to be a problem with tensorflow, causing ddb to not work. I'll look through it

**Comment by arenasys** [comment]
could be that the webui's venv has a different version of python than the version you are using to run helper.py.
the venv is using python 3.10 according to that error. run `python --version` to check what version you are running helper.py with

**Comment by Tortellin1** [comment]
![image](https://user-images.githubusercontent.com/117955345/201622147-081538a8-18b1-4132-aaa7-3c9aaa7dd8fa.png)
ah. that seems to be the case. how would I fix this? is there a command to change python versions?

huh?? this doesn't make sense 
![image](https://user-images.githubusercontent.com/117955345/201628285-5f738ed8-d718-4a5c-81c0-ed34354220e5.png)
edit: fixed it, it was a problem with path variable shenanigans (the order of paths). Now I will try to run it
