### ISSUE TITLE
global tags do not get appended/prepennded when using "filename" to write tags

### ISSUE THREAD

**Issue by ifeelagood** [arenatemp/sd-tagging-helper#22]
When writing to the txt file, the global tags work as intended. However, this does not work with filename mode. 

apologies for lack of PR, pretty busy atm

**Comment by arenasys** [comment]
fixed by 54995afe3f2e4b4650ddcbffd9c58ff56693f8cd
also i would not recommend using filename mode unless theres no other option, they get truncated due to OS filename length limits. max 250 characters for the full path on windows, max 250 characters for the filename on unix
