### ISSUE TITLE
Extension not working anymore on new install

### ISSUE THREAD

**Issue by neojam** [arenatemp/sd-tagging-helper#24]
Hi, 

looks like the extension is not working anymore, if you make a clean install of SD.
Maybe because of this commit?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c81d440d876dfd2ab3560410f37442ef56fc6632

missing now on new install:
\models\deepbooru

new:
\models\torch_deepdanbooru
(there is only "model-resnet_custom_v3.pt" in it)

```
DeprecationWarning: Support for PyQt5 is deprecated and will be removed in Pillow 10 (2023-07-01). Use PyQt6 or PySide6 instead.
  from PIL import Image, ImageDraw, ImageQt
STATUS: loaded 2 images, 0 have tags
...
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\stable-diffusio
n-webui\\models\\deepbooru\\tags.txt'
```

The extension works only on older installations of SD-webui if you still have "\models\deepbooru" folder with needed txt/json/etc files in it.
I copied the \models\deepbooru folder from an older backup to my new SD install dir to make your extension work again.

**Comment by arenasys** [comment]
moved to new version 9aed12a1349bdfd3db81bc707c19c7b2b15c42e2
