### ISSUE TITLE
How to start and how to add tags for dummies

### ISSUE THREAD

**Issue by ZnS-oscar** [arenatemp/sd-tagging-helper#25]
>The following content is extremely important for greenhands and dummies like me. I sincerely hope that the following content can be add to the newest version of `Readme`.
#  How to start
Firstly, Pillow and PyQt5 required
```python
pip install pillow pyqt5==5.15.7
```
Secondly, start the GUI
```python
python helper.py
```

# How to add tags
### What are these tag columns?
`Search..`
All the tags should be added to the tag pool before added to the image.
Search the tag you would like to add here to check if it is already in the tag pool.
If you cannot find your tag in the tag pool, you can add new tags here.
`Suggestions`
The tags you used will be here
`Favourites`
Move your mouse to the tag, you will see a star on the left to the tag. click it to light the star and then the tag is in the `favourites` column
`Active Tags` 
The tags that is going to be the added to the image.
###  How to add a brand new type of tag
 Type your new type of tag to the `Search...` bar, then click the `+`.
![Search bar](https://img-blog.csdnimg.cn/73e679edf27143fda31f8d2e88bc5b7f.png)
![plus mark](https://img-blog.csdnimg.cn/6a63ffdf56124745b95f7f6682f68423.png)

### How to add and delete a tag for the img
Double click(or select tag and press enter) any tag in the column of `Search..`, `Suggestions`, `Favourites`, then the tag will be in `Active Tags` column.  To delete tags, you need to select tag in `Active Tags` column and press enter(or delete)

**Comment by arenasys** [comment]
I have started to write up some information over at https://github.com/arenatemp/sd-tagging-helper/wiki

Also the font should be fixed now, didnt realise that was the default on some locales.
