### ISSUE TITLE
[feature request] Sort tags by alphabetical order 

### ISSUE THREAD

**Issue by denliner** [arenatemp/sd-tagging-helper#27]
Thank you for that useful tool.

I would really like to have the ability to sort tags by alphabetical order to keep some consistency between images that have been tagged with sd-tagging-helper and those that have been scraped from a booru.

**Comment by arenasys** [comment]
added in 9cbab95dfc560ca3e809e81ab381fe5733a89fa1. available in the edit menu, right clicking the existing sorting button or with `Ctrl+Y`.
I should say that tag order does matter for training, the starting tags of the prompt have more emphasis, so sorting alphabetically may not be optimal.
