### ISSUE TITLE
Addind different Crop ratios 

### ISSUE THREAD

**Issue by neojam** [arenatemp/sd-tagging-helper#29]
Hallo,

since most training apps support AR-Bucketing now:
https://github.com/NovelAI/novelai-aspect-ratio-bucketing
1:1 cropping is no longer necessary and also not desirable (having a whole Dataset consisting only of 1:1 images is bad practice)

So it would make sense allowing independent X/Y resolution for the cropping rectangle.

**Comment by arenasys** [comment]
For bucketing i would recommend packaging in `scale` or `original` mode to avoid cropping entirely. Support for rectangular crops would be nice, but its a big code change.

**Comment by neojam** [comment]
The problem with many images is, that they have lots of visual crap around the objects that you want to train.
Where its possible, i leave the images just as they are (no logos etc), but cropping is necessary in most cases if you want a good training dataset.
