### ISSUE TITLE
Crash cannot import name 'deepbooru_model

### ISSUE THREAD

**Issue by Cookie2243** [arenatemp/sd-tagging-helper#30]
2023-01-22 23:18:33.668276
Traceback (most recent call last):
  File "C:\Users\acmeuser\Desktop\sd-tagging-helper\helper.py", line 195, in load
    from modules import deepbooru_model
ImportError: cannot import name 'deepbooru_model' from 'modules' (C:\Users\acmeuser\AppData\Local\Programs\Python\Python310\lib\site-packages\modules.py)

When trying to use Interrogate button, I get the above error. I'm using the latest A1111.

**Comment by arenasys** [comment]
Deleting `C:\Users\acmeuser\AppData\Local\Programs\Python\Python310\lib\site-packages\modules.py` will fix it. Im not sure where that file is from but Its taking priority over the `modules` in the webui (despite the webui being put first in sys.path).

**Comment by Cookie2243** [comment]
Thank you that worked! :)
