### ISSUE TITLE
No module named 'deepdanbooru'

### ISSUE THREAD

**Issue by Lumoria** [arenatemp/sd-tagging-helper#5]
Not sure if I'm missing something here, but when I point to my automatic1111 root folder that has a working deepdanbooru, I get a crash with a log that prints:

`Traceback (most recent call last):
  File "/home/lumori/sd-tagging-helper/helper.py", line 208, in load
    import deepdanbooru as dd
ModuleNotFoundError: No module named 'deepdanbooru'`

**Comment by arenasys** [comment]
it will look for deepdanbooru in a few places:
```
stable-diffusion-webui/deepdanbooru
stable-diffusion-webui/models/deepbooru/deepdanbooru
stable-diffusion-webui/venv/Lib/site-packages/deepdanbooru
```
is yours somewhere different?

**Comment by Lumoria** [comment]
For some reason my file structure is way different than this. Maybe because I've cloned automatic1111 recently? But I've now manually cloned deepdanbooru into models and am now getting "No module named 'tensorflow". Where is my tensorflow supposed to be?

**Comment by arenasys** [comment]
are you running via `webui.sh` on linux or mac? only think i can think of that would cause this

**Comment by arenasys** [comment]
for the venv im seeing `stable-diffusion-webui/venv/lib/python3.10/site-packages/deepdanbooru` now. that python version wasnt there before

**Comment by Lumoria** [comment]
> for the venv im seeing `stable-diffusion-webui/venv/lib/python3.10/site-packages/deepdanbooru` now. that python version wasnt there before

Yes I'm running the webui.sh on Linux. And I tried moving the packages up to the lib folder but it still can't find tensorflow

**Comment by arenasys** [comment]
updated to be able to find the new venv site-packages. but if you moved it and still cant find tensorflow its a problem.
it should be in `site-packages` the same as `deepdanbooru` since the webui installs them both at the same time: `run_pip(f"install {deepdanbooru_package}#egg=deepdanbooru[tensorflow] tensorflow==2.10.0 tensorflow-io==0.27.0", "deepdanbooru")`

**Comment by arenasys** [comment]
oh wait its probably because it was a capital L in `venv/Lib/site-packages`, which only affected unix os's. just try with the latest commit and see if it works

**Comment by Lumoria** [comment]
> oh wait its probably because it was a capital L in `venv/Lib/site-packages`, which only affected unix os's. just try with the latest commit and see if it works

pulled the latest commit and everything works. Thanks man!
