### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by R3xpook** [arenatemp/sd-tagging-helper#6]
helper.py", line 762, in maxThreads
    return len(os.sched_getaffinity(0))
AttributeError: module 'os' has no attribute 'sched_getaffinity'

whathever trying to do anything it crash

**Comment by AiMiDi** [comment]
You can try my fix, the pull request has been made.
https://github.com/AiMiDi/sd-tagging-helper/tree/master

**Comment by arenasys** [comment]
fixed by 427a4eb602ea577e050cbfb6aaadaba4ddb2bdcb
